name: Test Orca Container Image action

on:
  workflow_dispatch:

jobs:
  container_scan_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan Container Image
        uses: ./
        with:
          api_token:
            ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key:
            "orcagithub"
          image:
            "alpine:3"
          format:
            "json"
          output:
            "results/"
          console_output: "table"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: orca-results
          path: results/